apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-commander.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-commander.name" . }}
    helm.sh/chart: {{ include "redis-commander.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis-commander.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "redis-commander.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REDIS_PORT
            value: "{{ .Values.rediscommander.REDIS_PORT }}"
          - name: REDIS_HOST
            value: "{{ .Values.rediscommander.REDIS_HOST }}"
          - name: REDIS_SOCKET
            value: "{{ .Values.rediscommander.REDIS_SOCKET }}"
          - name: REDIS_TLS
            value: "{{ .Values.rediscommander.REDIS_TLS }}"
          - name: REDIS_PASSWORD
            value: "{{ .Values.rediscommander.REDIS_PASSWORD }}"
          - name: REDIS_DB
            value: "{{ .Values.rediscommander.REDIS_DB }}"
          - name: REDIS_HOSTS
            value: "{{ .Values.rediscommander.REDIS_HOSTS }}"
          - name: SENTINEL_PORT
            value: "{{ .Values.rediscommander.SENTINEL_PORT }}"
          - name: SENTINEL_HOST
            value: "{{ .Values.rediscommander.SENTINEL_HOST }}"
          - name: SENTINELS
            value: "{{ .Values.rediscommander.SENTINELS }}"
          - name: CLIENT_MAX_BODY_SIZE
            value: "{{ .Values.rediscommander.SENTINEL_NAME }}"
          - name: SENTINEL_PASSWORD
            value: "{{ .Values.rediscommander.SENTINEL_PASSWORD }}"
          - name: K8S_SIGTERM
            value: "{{ .Values.rediscommander.K8S_SIGTERM }}"
          - name: HTTP_USER
            value: "{{ .Values.rediscommander.HTTP_USER }}"
          - name: HTTP_PASSWORD
            value: "{{ .Values.rediscommander.HTTP_PASSWORD }}"
          - name: HTTP_PASSWORD_HASH
            value: "{{ .Values.rediscommander.HTTP_PASSWORD_HASH }}"
          - name: ADDRESS
            value: "{{ .Values.rediscommander.ADDRESS }}"
          - name: PORT
            value: "{{ .Values.rediscommander.PORT }}"
          - name: READ_ONLY
            value: "{{ .Values.rediscommander.READ_ONLY }}"
          - name: URL_PREFIX
            value: "{{ .Values.rediscommander.URL_PREFIX }}"
          - name: URL_PREFIX
            value: "{{ .Values.rediscommander.URL_PREFIX }}"
          - name: NOSAVE
            value: "{{ .Values.rediscommander.NOSAVE }}"
          - name: NO_LOG_DATA
            value: "{{ .Values.rediscommander.NO_LOG_DATA }}"
          - name: FOLDING_CHAR
            value: "{{ .Values.rediscommander.FOLDING_CHAR }}"
          - name: SCAN_COUNT
            value: "{{ .Values.rediscommander.SCAN_COUNT }}"
          - name: FLUSH_ON_IMPORT
            value: "{{ .Values.rediscommander.FLUSH_ON_IMPORT }}"
          - name: REDIS_CONNECTION_NAME
            value: "{{ .Values.rediscommander.REDIS_CONNECTION_NAME }}"
          - name: REDIS_LABEL
            value: "{{ .Values.rediscommander.REDIS_LABEL }}"
          - name: CLIENT_MAX_BODY_SIZE
            value: "{{ .Values.rediscommander.CLIENT_MAX_BODY_SIZE }}"
          ports:
            - name: http
              containerPort: {{ .Values.rediscommander.PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
